"""Regenerate requirements-learning.txt: exact pins + sha256 of every usable wheel from PyPI.

Target: the app's bundled CPython 3.12 on macOS arm64. Only wheels are listed, so the app
installs with `pip install --only-binary=:all: --require-hashes -r requirements-learning.txt`.
The pins are this directory's working .venv (`pip freeze`), minus dev-only tools.

    .venv/bin/python lock_requirements.py            # rewrites requirements-learning.txt
"""
from __future__ import annotations

import json
import re
import subprocess
import sys
import urllib.request
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE / "requirements-learning.txt"
DEV_ONLY = {"pip", "ruff", "pytest", "iniconfig", "pluggy"}  # pygments stays: rich needs it
TAG = re.compile(r"-(?P<py>[^-]+)-(?P<abi>[^-]+)-(?P<plat>[^-]+)\.whl$")


def usable(filename: str) -> bool:
    m = TAG.search(filename)
    if not m:
        return False
    py, abi, plat = m["py"].split("."), m["abi"], m["plat"]
    py_ok = "cp312" in py or any(p in ("py3", "py2.py3") or p.startswith("py3") for p in py) \
        or (abi == "abi3" and any(p.startswith("cp3") and int(p[3:] or 0) <= 12 for p in py))
    plat_ok = plat == "any" or ("macosx" in plat and ("arm64" in plat or "universal2" in plat))
    return py_ok and plat_ok and (abi in ("none", "abi3", "cp312"))


def main() -> None:
    frozen = subprocess.run([sys.executable, "-m", "pip", "freeze", "--all"], check=True,
                            capture_output=True, text=True).stdout.split()
    pins = sorted((line.split("==") for line in frozen if "==" in line),
                  key=lambda p: p[0].lower())
    lines, total = [], 0
    for name, version in pins:
        if name.lower() in DEV_ONLY:
            continue
        with urllib.request.urlopen(f"https://pypi.org/pypi/{name}/{version}/json",
                                    timeout=30) as r:
            files = [f for f in json.loads(r.read())["urls"] if usable(f["filename"])]
        if not files:
            raise SystemExit(f"{name}=={version}: no macOS arm64 / cp312 wheel on PyPI")
        total += max(f["size"] for f in files)
        hashes = " \\\n    ".join(f"--hash=sha256:{f['digests']['sha256']}"
                                   for f in sorted(files, key=lambda f: f["filename"]))
        lines.append(f"{name}=={version} \\\n    {hashes}")
    header = [
        "# Galactus learning toolkit (laya + torch), generated by lock_requirements.py.",
        "# Target: bundled CPython 3.12, macOS arm64. Install into <app data>/learning/venv only:",
        "#   pip install --only-binary=:all: --require-hashes -r requirements-learning.txt",
        f"# download-bytes: {total}",
    ]
    OUT.write_text("\n".join(header + lines) + "\n", encoding="utf-8")
    print(f"{len(lines)} packages, {total / 1e6:.0f} MB -> {OUT.name}")


if __name__ == "__main__":
    main()
