// Galactus desktop, the bundled rust-analyzer driven over LSP.
//
// The app already ships rust-analyzer and the Rust standard library sources
// (see scripts/fetch-rust-tooling.sh). Until this module existed nothing drove
// them, so a .rs file got the Lezer grammar and 108 MB of the download was
// dead weight. This is the process side: spawn, frame, correlate, kill.
//
// THE SYSROOT, and why the fetch script pays for 70 MB of sources. A
// rust-analyzer with no sysroot resolves navigation inside the project but
// cannot resolve `std::` anything, and it does not degrade quietly: it reports
// unresolved-import errors on nearly every file. A server that underlines the
// whole buffer in red is strictly worse than no server, so `initialize` points
// `cargo.sysrootSrc` at the bundled `library/` and the sysroot itself at the
// path a real rustc reports, when this machine has one.
//
// WHAT THE SERVER IS NOT ALLOWED TO DO, decided here rather than at the call
// site. rust-analyzer is a build tool wearing a language server costume: build
// scripts, proc macros, `cargo check` on save and `workspace/executeCommand`
// all execute code that came out of the repository the user just opened. This
// app gates shell and file access behind an explicit permission prompt, so a
// language server must not become the way around it. Three defences, none of
// them optional:
//   * `buildScripts.enable` and `procMacro.enable` are false in the init
//     options, and `checkOnSave` is false, so opening a folder never compiles
//     anything. The cost is real (a crate whose API is generated by a build
//     script resolves worse) and it is the right trade for an offline app.
//   * `rust_lsp_request` accepts an ALLOWLIST of read-only methods. Anything
//     else is refused before it reaches the pipe, including the execute-command
//     family that runs cargo.
//   * nothing here writes a file. Rename produces a plan; the Code view turns
//     it into a proposal the user accepts hunk by hunk, like every other edit.
//
// Concurrency. One server at a time, under one mutex. Requests are correlated
// by JSON-RPC id through a pending map and answered on a channel, so the Tauri
// command can wait on the blocking pool without holding the lock and without
// touching the async runtime's threads. The reader is a plain OS thread parked
// in `read()`, which is what a pipe wants, and it is also the thread that
// answers the requests the SERVER sends US: leaving those unanswered is the
// classic way to make rust-analyzer wedge halfway through initialization.
//
// The framing codec and the URI encoder at the top are pure and are unit
// tested at the bottom of this file, because a header split across two reads
// is exactly the bug that only shows up on a slow machine.

use serde::Serialize;
use serde_json::{json, Value};
use std::collections::HashMap;
use std::io::{Read, Write};
use std::path::{Path, PathBuf};
use std::process::{Child, ChildStdin, Command, Stdio};
use std::sync::atomic::{AtomicI64, AtomicU64, Ordering};
use std::sync::mpsc::{channel, Receiver, Sender};
use std::sync::{Mutex, OnceLock};
use std::time::{Duration, Instant};

/// Event name the frontend listens on. One channel for every kind of
/// unsolicited traffic, discriminated by `kind`, so the frontend registers a
/// single listener and cannot miss a message by forgetting a name.
pub const EVENT: &str = "galactus://rust-lsp";

/// How long `initialize` may take. rust-analyzer answers `initialize` before it
/// has indexed anything, so this is a startup budget, not an indexing budget:
/// thirty seconds means the process is wedged, not that the project is big.
pub const INIT_DEADLINE: Duration = Duration::from_secs(30);

/// Default budget for one request. Hover on a cold cache can genuinely take
/// seconds while the crate graph is still being built.
pub const DEFAULT_REQUEST_DEADLINE: Duration = Duration::from_secs(20);

/// A header block bigger than this is not a header block. Bounded so a server
/// that starts emitting garbage cannot grow our buffer without limit.
const MAX_HEADER_BYTES: usize = 8 * 1024;

/// Refuse absurd Content-Length values before allocating for them.
const MAX_MESSAGE_BYTES: usize = 64 * 1024 * 1024;

/// How much of the server's stderr to keep for the error message.
const STDERR_TAIL_BYTES: usize = 8 * 1024;

/// Shown when the bundle carries no server. Fail closed and say why: the user
/// can act on "reinstall", not on a silent absence of hovers.
pub const NO_SERVER: &str =
    "rust-analyzer is not in this build of Galactus: .rs files keep syntax highlighting, \
     outline and syntax errors, but no types, no hover and no go to definition";

// ---------------------------------------------------------------- framing

/// Incremental decoder for the LSP wire format: `Content-Length: N\r\n\r\n`
/// followed by N bytes of UTF-8 JSON.
///
/// Incremental because a pipe read returns whatever happened to be in the
/// buffer: the header can arrive split down the middle of `Content-Length`,
/// and a 200 kB hover response arrives as a dozen chunks. Feeding a
/// `BufReader::read_line` loop looks simpler and is, right up to the day a
/// server writes a bare `\n` inside a JSON string and the line reader cuts the
/// body in half.
#[derive(Default)]
pub struct FrameDecoder {
    buf: Vec<u8>,
    /// Body length once the header has been consumed.
    need: Option<usize>,
}

impl FrameDecoder {
    pub fn new() -> Self {
        Self::default()
    }

    pub fn push(&mut self, bytes: &[u8]) {
        self.buf.extend_from_slice(bytes);
    }

    /// Pull the next complete message, if there is one.
    ///
    /// `Ok(None)` means "not yet, feed me more". `Err` means the stream is not
    /// LSP any more and the caller must stop reading it: once a header is
    /// unparseable there is no way to find where the next one starts, and
    /// guessing produces a decoder that silently drops half the traffic.
    pub fn next_message(&mut self) -> Result<Option<String>, String> {
        if self.need.is_none() {
            let end = match find(&self.buf, b"\r\n\r\n") {
                Some(i) => i,
                None => {
                    if self.buf.len() > MAX_HEADER_BYTES {
                        return Err(format!(
                            "no LSP header in the first {MAX_HEADER_BYTES} bytes"
                        ));
                    }
                    return Ok(None);
                }
            };
            let header = String::from_utf8_lossy(&self.buf[..end]).into_owned();
            let len = parse_content_length(&header)?;
            if len > MAX_MESSAGE_BYTES {
                return Err(format!("message announces {len} bytes, over the limit"));
            }
            self.buf.drain(..end + 4);
            self.need = Some(len);
        }
        let want = self.need.expect("set just above");
        if self.buf.len() < want {
            return Ok(None);
        }
        let body: Vec<u8> = self.buf.drain(..want).collect();
        self.need = None;
        String::from_utf8(body).map(Some).map_err(|e| format!("message is not UTF-8: {e}"))
    }
}

fn find(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    if needle.is_empty() || haystack.len() < needle.len() {
        return None;
    }
    haystack.windows(needle.len()).position(|w| w == needle)
}

/// Read Content-Length out of a header block. Unknown fields are ignored, as
/// the specification requires; a missing or unparseable length is fatal.
fn parse_content_length(header: &str) -> Result<usize, String> {
    let mut found: Option<usize> = None;
    for line in header.split("\r\n") {
        if line.is_empty() {
            continue;
        }
        let (name, value) = match line.split_once(':') {
            Some(p) => p,
            None => return Err(format!("malformed LSP header line: {line:?}")),
        };
        if !name.trim().eq_ignore_ascii_case("content-length") {
            continue;
        }
        found = Some(
            value
                .trim()
                .parse::<usize>()
                .map_err(|_| format!("bad Content-Length: {:?}", value.trim()))?,
        );
    }
    found.ok_or_else(|| "LSP header without Content-Length".to_string())
}

/// Frame one payload for the wire. No Content-Type: it is optional, and
/// rust-analyzer rejects the charset spelling some clients still send.
pub fn encode(payload: &str) -> Vec<u8> {
    let mut out = Vec::with_capacity(payload.len() + 32);
    out.extend_from_slice(format!("Content-Length: {}\r\n\r\n", payload.len()).as_bytes());
    out.extend_from_slice(payload.as_bytes());
    out
}

// ---------------------------------------------------------------- uri

/// Percent-encode one path segment byte by byte.
///
/// Deliberately conservative: everything outside the RFC 3986 unreserved set
/// is escaped, `/` excepted because it is the separator. A workspace under
/// `/Volumes/NoxalisExtended/Noxalis Lab/...` is the normal case on this
/// project, and a raw space in a URI makes rust-analyzer answer about a file
/// it never opened rather than fail loudly.
pub fn path_to_uri(path: &Path) -> String {
    let raw = path.to_string_lossy();
    let mut out = String::from("file://");
    for b in raw.as_bytes() {
        let c = *b as char;
        if c.is_ascii_alphanumeric() || matches!(c, '-' | '.' | '_' | '~' | '/') {
            out.push(c);
        } else {
            out.push_str(&format!("%{b:02X}"));
        }
    }
    out
}

// ---------------------------------------------------------------- allowlist

/// Requests the frontend may issue. Read-only by construction.
///
/// `workspace/executeCommand` is absent on purpose: rust-analyzer exposes
/// `rust-analyzer.runSingle` and friends there, which spawn cargo with
/// arguments taken from the opened project. `textDocument/formatting` is
/// absent too, for a smaller version of the same reason: it shells out to the
/// project's rustfmt, and formatting is not what this feature is for.
const ALLOWED_REQUESTS: &[&str] = &[
    "textDocument/hover",
    "textDocument/definition",
    "textDocument/typeDefinition",
    "textDocument/implementation",
    "textDocument/references",
    "textDocument/documentSymbol",
    "textDocument/documentHighlight",
    "textDocument/completion",
    "textDocument/signatureHelp",
    "textDocument/prepareRename",
    "textDocument/rename",
    "textDocument/inlayHint",
    "textDocument/foldingRange",
    "completionItem/resolve",
    "workspace/symbol",
];

/// Notifications the frontend may send. Document synchronisation and nothing
/// else: `didSave` is excluded because a save is what would trigger a check.
const ALLOWED_NOTIFICATIONS: &[&str] = &[
    "textDocument/didOpen",
    "textDocument/didChange",
    "textDocument/didClose",
    "$/cancelRequest",
];

pub fn request_allowed(method: &str) -> bool {
    ALLOWED_REQUESTS.contains(&method)
}

pub fn notification_allowed(method: &str) -> bool {
    ALLOWED_NOTIFICATIONS.contains(&method)
}

// ---------------------------------------------------------------- resolution

/// Bundle Resources dir (packaged app), the src-tauri dir (dev run), or the
/// crate dir (cargo test). A deliberate twin of lib.rs::resource_dir and of
/// pylang.rs's copy, for the same reason those two are twins: this module must
/// resolve its own tooling without reaching into the app.
fn resource_dir() -> Option<PathBuf> {
    let has = |p: &PathBuf| p.join("rust-tooling").exists();
    if let Ok(exe) = std::env::current_exe() {
        if let Some(res) = exe.parent().and_then(|p| p.parent()).map(|p| p.join("Resources")) {
            if has(&res) {
                return Some(res);
            }
        }
    }
    let cwd = std::env::current_dir().unwrap_or_default();
    if has(&cwd) {
        return Some(cwd);
    }
    let dev = cwd.join("src-tauri");
    if has(&dev) {
        return Some(dev);
    }
    #[cfg(debug_assertions)]
    {
        let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        if has(&manifest) {
            return Some(manifest);
        }
    }
    None
}

/// The bundled server and the bundled `library/` directory of std sources.
/// `GALACTUS_RUST_ANALYZER` and `GALACTUS_RUST_SRC` override both, which is how
/// a test points at a checkout copy.
pub fn tooling() -> Option<(PathBuf, PathBuf)> {
    let env_bin = std::env::var("GALACTUS_RUST_ANALYZER").ok().filter(|s| !s.is_empty());
    let env_src = std::env::var("GALACTUS_RUST_SRC").ok().filter(|s| !s.is_empty());
    if let (Some(b), Some(s)) = (&env_bin, &env_src) {
        let (b, s) = (PathBuf::from(b), PathBuf::from(s));
        if b.is_file() && s.is_dir() {
            return Some((b, s));
        }
    }
    let root = resource_dir()?.join("rust-tooling");
    let bin = root.join("rust-analyzer");
    let src = root.join("rust-src/library");
    if bin.is_file() && src.is_dir() {
        ensure_executable(&bin);
        Some((bin, src))
    } else {
        None
    }
}

fn ensure_executable(p: &Path) {
    // Resource copying does not preserve the executable bit, exactly as
    // lib.rs::bundled_engine documents for llama-server.
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        if let Ok(meta) = std::fs::metadata(p) {
            let mut perm = meta.permissions();
            if perm.mode() & 0o111 == 0 {
                perm.set_mode(0o755);
                let _ = std::fs::set_permissions(p, perm);
            }
        }
    }
    let _ = p;
}

/// The sysroot a real rustc reports, when this machine has one.
///
/// Asking rustc beats rust-analyzer's own `"discover"`: discovery runs the
/// rustup shim through PATH, and this app resolves tools with toolchain.rs
/// precisely so that a PATH lookup never decides what gets spawned. Without a
/// rustc the answer is None and the server runs on the bundled sources alone,
/// which is enough for `std::` and not enough for the project's dependencies.
fn discover_sysroot() -> Option<PathBuf> {
    let rustc = crate::toolchain::resolve("rustc")?;
    let out = Command::new(rustc)
        .arg("--print")
        .arg("sysroot")
        .stdin(Stdio::null())
        .output()
        .ok()?;
    if !out.status.success() {
        return None;
    }
    let p = PathBuf::from(String::from_utf8_lossy(&out.stdout).trim().to_string());
    if p.is_dir() {
        Some(p)
    } else {
        None
    }
}

// ---------------------------------------------------------------- state

/// Where unsolicited traffic goes. A closure rather than an `AppHandle` so the
/// session can be driven from a test with no Tauri app and no window.
pub type Sink = Box<dyn Fn(Value) + Send + Sync>;

struct Session {
    child: Child,
    stdin: ChildStdin,
    root: PathBuf,
    root_uri: String,
    server: String,
    sysroot: Option<String>,
    sysroot_src: String,
    cargo: bool,
}

fn session() -> &'static Mutex<Option<Session>> {
    static S: OnceLock<Mutex<Option<Session>>> = OnceLock::new();
    S.get_or_init(|| Mutex::new(None))
}

/// Serialises `start` and `stop` end to end.
///
/// The session mutex alone is NOT enough, and the gap is a process leak.
/// `start` clears the session, spawns, then assigns, releasing the session
/// lock between each step. Two concurrent starts can therefore both find
/// nothing running, both spawn, and the second assignment DROPS the first
/// `Session`. `std::process::Child` has no `Drop` that kills, so that first
/// rust-analyzer keeps running, is no longer reachable through `session()`,
/// and neither `stop()` nor `shutdown_all()` on the exit path can ever reap
/// it: a whole crate index left in RAM after the app has quit.
///
/// Two concurrent starts are reachable from the app: `enableRustLsp` is async
/// and two callers can both get past their teardown before either spawns.
fn lifecycle_lock() -> &'static Mutex<()> {
    static L: OnceLock<Mutex<()>> = OnceLock::new();
    L.get_or_init(|| Mutex::new(()))
}

type Pending = HashMap<i64, Sender<Result<Value, String>>>;

fn pending() -> &'static Mutex<Pending> {
    static P: OnceLock<Mutex<Pending>> = OnceLock::new();
    P.get_or_init(|| Mutex::new(HashMap::new()))
}

/// Ids are unique for the life of the process, not per session, so a late
/// answer from a killed server can never be matched to a new request.
static NEXT_ID: AtomicI64 = AtomicI64::new(1);

/// Bumped on every start and every stop. The reader thread carries its own
/// copy and stops touching shared state as soon as it no longer matches, which
/// is what keeps a dying server from tearing down the one that replaced it.
static GENERATION: AtomicU64 = AtomicU64::new(0);

/// Last words of a dead server, for the error message.
fn stderr_tail() -> &'static Mutex<String> {
    static E: OnceLock<Mutex<String>> = OnceLock::new();
    E.get_or_init(|| Mutex::new(String::new()))
}

#[derive(Serialize, Clone, Debug, Default)]
pub struct LspStatus {
    pub running: bool,
    pub root: Option<String>,
    pub root_uri: Option<String>,
    /// The server's own version string, as `rust-analyzer --version` prints it.
    pub server: Option<String>,
    pub sysroot: Option<String>,
    pub sysroot_src: Option<String>,
    /// A real cargo was found. Without one the crate graph of the user's own
    /// dependencies cannot be built, and the UI must not promise otherwise.
    pub cargo: bool,
    pub pid: Option<u32>,
    /// Non-fatal limitation, in plain words, for the badge tooltip.
    pub note: Option<String>,
}

pub fn status() -> LspStatus {
    let guard = session().lock().unwrap_or_else(|e| e.into_inner());
    match guard.as_ref() {
        None => LspStatus::default(),
        Some(s) => LspStatus {
            running: true,
            root: Some(s.root.display().to_string()),
            root_uri: Some(s.root_uri.clone()),
            server: Some(s.server.clone()),
            sysroot: s.sysroot.clone(),
            sysroot_src: Some(s.sysroot_src.clone()),
            cargo: s.cargo,
            pid: Some(s.child.id()),
            note: note_for(s.cargo, s.sysroot.is_some()),
        },
    }
}

fn note_for(cargo: bool, sysroot: bool) -> Option<String> {
    if cargo {
        return None;
    }
    Some(
        if sysroot {
            "no cargo on this Mac: the standard library resolves, the project's own \
             dependencies do not"
        } else {
            "no Rust toolchain on this Mac: only the bundled standard library sources \
             resolve, and nothing from the project's dependencies"
        }
        .to_string(),
    )
}

// ---------------------------------------------------------------- transport

/// Serialise one JSON value onto the pipe. Holds the session lock for the
/// duration of the write and nothing more: a caller that waits for an answer
/// must do it after this returns, or two requests deadlock each other.
fn write_message(value: &Value) -> Result<(), String> {
    let text = serde_json::to_string(value).map_err(|e| e.to_string())?;
    let mut guard = session().lock().unwrap_or_else(|e| e.into_inner());
    let s = guard.as_mut().ok_or("the Rust language server is not running")?;
    s.stdin
        .write_all(&encode(&text))
        .and_then(|_| s.stdin.flush())
        .map_err(|e| format!("cannot write to the Rust language server: {e}"))
}

/// Post a request and hand back its id plus the channel the answer will arrive
/// on. The id comes back rather than being re-read from the counter: another
/// thread can allocate an id between the two reads, and cancelling somebody
/// else's request is a bug that only appears under two users of one server.
fn enqueue(method: &str, params: Value) -> Result<(i64, Receiver<Result<Value, String>>), String> {
    let id = NEXT_ID.fetch_add(1, Ordering::SeqCst);
    let (tx, rx) = channel();
    pending().lock().unwrap_or_else(|e| e.into_inner()).insert(id, tx);
    let message = json!({"jsonrpc": "2.0", "id": id, "method": method, "params": params});
    if let Err(e) = write_message(&message) {
        pending().lock().unwrap_or_else(|e| e.into_inner()).remove(&id);
        return Err(e);
    }
    Ok((id, rx))
}

/// A request, start to finish. `$/cancelRequest` is sent on expiry so the
/// server stops working on an answer nobody will read.
fn request(method: &str, params: Value, deadline: Duration) -> Result<Value, String> {
    let (id, rx) = enqueue(method, params)?;
    match rx.recv_timeout(deadline) {
        Ok(v) => v,
        Err(_) => {
            pending().lock().unwrap_or_else(|e| e.into_inner()).remove(&id);
            let _ = write_message(&json!({
                "jsonrpc": "2.0", "method": "$/cancelRequest", "params": {"id": id}
            }));
            Err(format!("{method} did not answer within {deadline:?}"))
        }
    }
}

fn notify(method: &str, params: Value) -> Result<(), String> {
    write_message(&json!({"jsonrpc": "2.0", "method": method, "params": params}))
}

/// Every waiting caller gets the same failure, once, when the server dies.
fn fail_pending(reason: &str) {
    let drained: Vec<Sender<Result<Value, String>>> = {
        let mut map = pending().lock().unwrap_or_else(|e| e.into_inner());
        map.drain().map(|(_, tx)| tx).collect()
    };
    for tx in drained {
        let _ = tx.send(Err(reason.to_string()));
    }
}

// ---------------------------------------------------------------- reader

/// The one thread that reads the server's stdout.
///
/// Three kinds of traffic arrive here and all three must be handled, which is
/// the part a naive client gets wrong:
///   * responses, matched to a waiting caller by id;
///   * notifications, forwarded to the frontend (diagnostics and progress);
///   * REQUESTS FROM THE SERVER. rust-analyzer asks the client to create a
///     progress token before it starts indexing and blocks its own startup
///     until the answer comes back. An unknown server request gets a proper
///     JSON-RPC MethodNotFound error rather than silence, because silence is
///     what makes the server sit there forever looking like a hang.
fn reader_loop(mut stdout: std::process::ChildStdout, generation: u64, sink: Sink) {
    let mut decoder = FrameDecoder::new();
    let mut chunk = [0u8; 16 * 1024];
    let ended: String = loop {
        let n = match stdout.read(&mut chunk) {
            Ok(0) => break "the Rust language server closed its output".to_string(),
            Ok(n) => n,
            Err(e) => break format!("cannot read from the Rust language server: {e}"),
        };
        decoder.push(&chunk[..n]);
        loop {
            match decoder.next_message() {
                Ok(None) => break,
                Ok(Some(text)) => dispatch(&text, &sink),
                // Unparseable framing: the stream cannot be resynchronised, so
                // the session is over. Reporting it beats decoding noise.
                Err(e) => {
                    finish(generation, &format!("the Rust language server sent {e}"), &sink);
                    return;
                }
            }
        }
    };
    finish(generation, &ended, &sink);
}

fn dispatch(text: &str, sink: &Sink) {
    let value: Value = match serde_json::from_str(text) {
        Ok(v) => v,
        // One bad message is survivable; framing was intact, so the next one
        // still starts where it should.
        Err(_) => return,
    };
    let has_id = value.get("id").map(|v| !v.is_null()).unwrap_or(false);
    let method = value.get("method").and_then(|m| m.as_str()).map(str::to_string);

    match (has_id, method) {
        // Response to something we asked.
        (true, None) => {
            let id = match value.get("id").and_then(Value::as_i64) {
                Some(i) => i,
                None => return,
            };
            let tx = pending().lock().unwrap_or_else(|e| e.into_inner()).remove(&id);
            if let Some(tx) = tx {
                let answer = if let Some(err) = value.get("error") {
                    Err(lsp_error_message(err))
                } else {
                    Ok(value.get("result").cloned().unwrap_or(Value::Null))
                };
                let _ = tx.send(answer);
            }
        }
        // Request FROM the server.
        (true, Some(m)) => {
            let id = value.get("id").cloned().unwrap_or(Value::Null);
            let reply = match m.as_str() {
                // Accepting the token is what lets us report indexing progress.
                "window/workDoneProgress/create" | "client/registerCapability"
                | "client/unregisterCapability" => {
                    json!({"jsonrpc": "2.0", "id": id, "result": Value::Null})
                }
                _ => json!({
                    "jsonrpc": "2.0", "id": id,
                    "error": {"code": -32601, "message": format!("{m} is not supported by this client")}
                }),
            };
            let _ = write_message(&reply);
        }
        // Notification.
        (false, Some(m)) => {
            let params = value.get("params").cloned().unwrap_or(Value::Null);
            match m.as_str() {
                "textDocument/publishDiagnostics" => {
                    sink(json!({"kind": "diagnostics", "params": params}))
                }
                "$/progress" => sink(json!({"kind": "progress", "params": params})),
                "window/logMessage" | "window/showMessage" => {
                    sink(json!({"kind": "log", "params": params}))
                }
                _ => {}
            }
        }
        (false, None) => {}
    }
}

fn lsp_error_message(err: &Value) -> String {
    let message = err.get("message").and_then(Value::as_str).unwrap_or("unknown error");
    match err.get("code").and_then(Value::as_i64) {
        Some(code) => format!("{message} (LSP error {code})"),
        None => message.to_string(),
    }
}

/// The session is over: unblock every waiter and tell the frontend, but only
/// if this reader still owns the current generation. A restart that overlapped
/// with a dying server must not have its state torn down by the corpse.
fn finish(generation: u64, reason: &str, sink: &Sink) {
    if GENERATION.load(Ordering::SeqCst) != generation {
        return;
    }
    let tail = stderr_tail().lock().unwrap_or_else(|e| e.into_inner()).clone();
    let detail = last_lines(&tail, 3);
    let full = if detail.is_empty() {
        reason.to_string()
    } else {
        format!("{reason}: {detail}")
    };
    {
        let mut guard = session().lock().unwrap_or_else(|e| e.into_inner());
        if let Some(mut s) = guard.take() {
            let _ = s.child.kill();
            let _ = s.child.wait();
        }
    }
    fail_pending(&full);
    sink(json!({"kind": "stopped", "reason": full}));
}

fn last_lines(s: &str, n: usize) -> String {
    let lines: Vec<&str> = s.lines().filter(|l| !l.trim().is_empty()).collect();
    lines[lines.len().saturating_sub(n)..].join(" / ")
}

// ---------------------------------------------------------------- lifecycle

/// Start a server for one workspace root. Blocking: call it off the UI thread.
///
/// Idempotent in the only way that matters: an existing session is stopped
/// first, so a second call cannot leave an orphan holding a gigabyte of index.
pub fn start(root: &Path, sink: Sink) -> Result<LspStatus, String> {
    if !root.is_dir() {
        return Err(format!("{} is not a folder", root.display()));
    }
    let (bin, src) = tooling().ok_or(NO_SERVER)?;
    // Held for the whole function, see lifecycle_lock. `stop_locked` and not
    // `stop`, because the lock is not reentrant and `stop` takes it too.
    let _serialised = lifecycle_lock().lock().unwrap_or_else(|e| e.into_inner());
    stop_locked();

    let generation = GENERATION.fetch_add(1, Ordering::SeqCst) + 1;
    let version = server_version(&bin);
    let sysroot = discover_sysroot();
    let cargo = crate::toolchain::resolve("cargo").is_some();

    let mut child = Command::new(&bin)
        .current_dir(root)
        // rust-analyzer picks up RA_LOG and friends; an inherited value from a
        // developer shell would turn stderr into a firehose inside the app.
        .env_remove("RA_LOG")
        .env_remove("RUST_LOG")
        .env_remove("RA_PROFILE")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .map_err(|e| format!("cannot start the bundled rust-analyzer ({}): {e}", bin.display()))?;

    let stdin = child.stdin.take().ok_or("no stdin pipe")?;
    let stdout = child.stdout.take().ok_or("no stdout pipe")?;
    let stderr = child.stderr.take().ok_or("no stderr pipe")?;
    stderr_tail().lock().unwrap_or_else(|e| e.into_inner()).clear();

    let root_uri = path_to_uri(root);
    *session().lock().unwrap_or_else(|e| e.into_inner()) = Some(Session {
        child,
        stdin,
        root: root.to_path_buf(),
        root_uri: root_uri.clone(),
        server: version.clone(),
        sysroot: sysroot.as_ref().map(|p| p.display().to_string()),
        sysroot_src: src.display().to_string(),
        cargo,
    });

    // stderr is drained on its own thread and kept bounded: an undrained pipe
    // fills, and a server blocked writing a log line looks exactly like a hang.
    std::thread::spawn(move || {
        let mut reader = stderr;
        let mut chunk = [0u8; 4096];
        while let Ok(n) = reader.read(&mut chunk) {
            if n == 0 {
                break;
            }
            let mut tail = stderr_tail().lock().unwrap_or_else(|e| e.into_inner());
            tail.push_str(&String::from_utf8_lossy(&chunk[..n]));
            if tail.len() > STDERR_TAIL_BYTES {
                let cut = tail.len() - STDERR_TAIL_BYTES;
                *tail = tail[cut..].to_string();
            }
        }
    });

    std::thread::spawn(move || reader_loop(stdout, generation, sink));

    let params = initialize_params(root, &root_uri, &src, sysroot.as_deref());
    let result = match request("initialize", params, INIT_DEADLINE) {
        Ok(v) => v,
        Err(e) => {
            // A server that cannot initialize is not a server. Take it down
            // rather than leave a process that answers later requests with junk.
            stop();
            return Err(e);
        }
    };
    check_position_encoding(&result)?;
    notify("initialized", json!({}))?;

    Ok(status())
}

/// The version line, for the badge tooltip. Cheap and worth having: a stale
/// bundle is otherwise indistinguishable from a fresh one.
fn server_version(bin: &Path) -> String {
    Command::new(bin)
        .arg("--version")
        .stdin(Stdio::null())
        .output()
        .ok()
        .filter(|o| o.status.success())
        .map(|o| String::from_utf8_lossy(&o.stdout).trim().to_string())
        .filter(|s| !s.is_empty())
        .unwrap_or_else(|| "rust-analyzer (version unknown)".to_string())
}

/// We offer utf-16 and nothing else, so the server has to answer utf-16.
///
/// This is the single most expensive mistake available in an LSP client. A
/// JavaScript string is UTF-16 code units, so utf-16 positions map to editor
/// offsets with no conversion at all; accept utf-8 by accident and every line
/// containing an accent, an emoji or a box-drawing character reports its
/// columns a few units off, which shows up as a hover on the wrong token and
/// a rename that eats a neighbouring character.
fn check_position_encoding(init_result: &Value) -> Result<(), String> {
    let encoding = init_result
        .get("capabilities")
        .and_then(|c| c.get("positionEncoding"))
        .and_then(Value::as_str)
        // Absent means the pre-3.17 default, which is utf-16.
        .unwrap_or("utf-16");
    if encoding == "utf-16" {
        Ok(())
    } else {
        stop();
        Err(format!(
            "the Rust language server insists on {encoding} positions, which this editor \
             cannot map safely"
        ))
    }
}

fn initialize_params(root: &Path, root_uri: &str, sysroot_src: &Path, sysroot: Option<&Path>) -> Value {
    json!({
        "processId": std::process::id(),
        "rootUri": root_uri,
        "rootPath": root.display().to_string(),
        "workspaceFolders": [{
            "uri": root_uri,
            "name": root.file_name().map(|n| n.to_string_lossy().to_string()).unwrap_or_default(),
        }],
        "clientInfo": {"name": "Galactus"},
        "capabilities": {
            "general": {"positionEncodings": ["utf-16"]},
            "window": {
                // True so the server creates a progress token and we can tell
                // the user that answers are incomplete while it indexes.
                "workDoneProgress": true,
                "showMessage": {"messageActionItem": {"additionalPropertiesSupport": false}}
            },
            "workspace": {
                // Both false so the server never asks us a question we would
                // have to answer well: it reads initializationOptions instead.
                "configuration": false,
                "workspaceFolders": false,
                "applyEdit": false,
                "symbol": {"dynamicRegistration": false}
            },
            "textDocument": {
                "synchronization": {
                    "dynamicRegistration": false,
                    "didSave": false,
                    "willSave": false
                },
                "publishDiagnostics": {"relatedInformation": true, "versionSupport": true},
                "hover": {"contentFormat": ["markdown", "plaintext"]},
                "definition": {"linkSupport": false},
                "references": {"dynamicRegistration": false},
                "documentSymbol": {"hierarchicalDocumentSymbolSupport": true},
                "completion": {
                    "completionItem": {
                        "snippetSupport": false,
                        "documentationFormat": ["plaintext", "markdown"],
                        "resolveSupport": {"properties": ["documentation", "detail"]}
                    },
                    "contextSupport": true
                },
                "rename": {"prepareSupport": true},
                "signatureHelp": {
                    "signatureInformation": {"documentationFormat": ["plaintext"]}
                }
            }
        },
        "initializationOptions": {
            "cargo": {
                // A path, or null. Never "discover": see discover_sysroot.
                "sysroot": sysroot.map(|p| Value::from(p.display().to_string())).unwrap_or(Value::Null),
                // The bundled sources. Set even when a sysroot was found, so a
                // toolchain installed without the rust-src component still
                // resolves std instead of underlining every use of it.
                "sysrootSrc": sysroot_src.display().to_string(),
                "buildScripts": {"enable": false}
                // `cargo.autoreload: false` used to be here and MUST NOT come
                // back. Measured against rust-analyzer 0.3.2997 by bisecting
                // the init options one key at a time: with it set, the crate
                // graph never finishes loading, every hover answers null
                // forever and the server reports no error at all, so it looks
                // exactly like an indexing pass that never ends. Everything
                // else in this block was cleared the same way.
            },
            // Both of these execute code that came with the repository.
            "procMacro": {"enable": false},
            "checkOnSave": false,
            // Measured on this repo: priming walks all 256 crates of the
            // dependency graph and burns minutes of CPU before answering
            // anything. Hover and go to definition work perfectly without it,
            // computed on demand, so the whole cost buys a slightly faster
            // second request in exchange for a fan that never stops.
            "cachePriming": {"enable": false},
            "files": {
                "excludeDirs": ["target", "node_modules", ".git", "dist", "build", ".venv"]
            },
            "diagnostics": {"enable": true, "experimental": {"enable": false}},
            "hover": {"documentation": {"keywords": {"enable": false}}}
        }
    })
}

/// Stop the server. Graceful first (`shutdown` then `exit`, which is what lets
/// rust-analyzer flush its on-disk cache), then a kill, always.
///
/// Never fails and never blocks for long: it runs on the app's exit path, and
/// an exit path that can hang is a bug report about a beachball.
pub fn stop() {
    let _serialised = lifecycle_lock().lock().unwrap_or_else(|e| e.into_inner());
    stop_locked();
}

/// The body of `stop`, for callers that already hold `lifecycle_lock`.
fn stop_locked() {
    let running = session().lock().unwrap_or_else(|e| e.into_inner()).is_some();
    if !running {
        return;
    }
    // Retire the generation first: the reader thread is about to see EOF and
    // must not report that as a crash the user needs to know about.
    GENERATION.fetch_add(1, Ordering::SeqCst);

    if let Ok((_, rx)) = enqueue("shutdown", Value::Null) {
        let _ = rx.recv_timeout(Duration::from_secs(3));
    }
    let _ = notify("exit", Value::Null);

    // Take the session OUT of the mutex before waiting on the process. The
    // reader thread answers server requests, which needs this same lock, and
    // holding it across a two second wait would be a two second stall on the
    // exit path for no benefit.
    let taken = session().lock().unwrap_or_else(|e| e.into_inner()).take();
    if let Some(mut s) = taken {
        // Dropping stdin closes the pipe, which is a second, independent reason
        // for the server to exit: rust-analyzer stops on EOF.
        drop(s.stdin);
        let deadline = Instant::now() + Duration::from_secs(2);
        loop {
            match s.child.try_wait() {
                Ok(Some(_)) => break,
                Ok(None) if Instant::now() < deadline => {
                    std::thread::sleep(Duration::from_millis(20))
                }
                _ => {
                    let _ = s.child.kill();
                    let _ = s.child.wait();
                    break;
                }
            }
        }
    }
    fail_pending("the Rust language server was stopped");
}

/// Called from the app's Exit handler. An abandoned rust-analyzer keeps a
/// whole crate index in RAM and, unlike a window, nothing on screen says so.
pub fn shutdown_all() {
    stop();
}

// ---------------------------------------------------------------- commands

/// Start the server for `root`. Async so Tauri keeps it off the UI thread; the
/// work runs on the blocking pool because it waits on a child process.
#[tauri::command]
pub async fn rust_lsp_start(app: tauri::AppHandle, root: String) -> Result<LspStatus, String> {
    tauri::async_runtime::spawn_blocking(move || {
        let sink: Sink = Box::new(move |payload: Value| {
            use tauri::Emitter;
            let _ = app.emit(EVENT, payload);
        });
        start(Path::new(&root), sink)
    })
    .await
    .map_err(|e| format!("the Rust language server thread died: {e}"))?
}

#[tauri::command]
pub async fn rust_lsp_stop() -> Result<(), String> {
    tauri::async_runtime::spawn_blocking(stop)
        .await
        .map_err(|e| format!("the Rust language server thread died: {e}"))
}

/// Async and on the blocking pool like the rest, and for the reason spelled
/// out on `rust_lsp_notify` below: a Tauri command declared `fn` runs on the
/// MAIN thread, and `status()` takes the session mutex, which `write_message`
/// holds across a blocking `write_all` of a whole buffer. A synchronous
/// version therefore parks the webview's main thread for as long as a
/// multi-megabyte `didChange` takes to drain, which is precisely when the
/// server is busy and slow to read.
#[tauri::command]
pub async fn rust_lsp_status() -> Result<LspStatus, String> {
    tauri::async_runtime::spawn_blocking(status)
        .await
        .map_err(|e| format!("the Rust language server thread died: {e}"))
}

/// Issue one request. Refused outright when the method is not on the read-only
/// allowlist, so the frontend cannot be talked into asking the server to build.
#[tauri::command]
pub async fn rust_lsp_request(
    method: String,
    params: Value,
    timeout_ms: Option<u64>,
) -> Result<Value, String> {
    if !request_allowed(&method) {
        return Err(format!("{method} is not allowed: this client is read-only"));
    }
    let deadline = timeout_ms
        .map(Duration::from_millis)
        .unwrap_or(DEFAULT_REQUEST_DEADLINE);
    tauri::async_runtime::spawn_blocking(move || request(&method, params, deadline))
        .await
        .map_err(|e| format!("the Rust language server thread died: {e}"))?
}

/// Send one notification. Same allowlist rule.
///
/// Async like the rest, even though there is no answer to wait for: a Tauri
/// command declared `fn` runs on the MAIN thread, and `didChange` carries the
/// whole buffer. A pipe write blocks once the kernel buffer is full, so a
/// synchronous version would freeze the window whenever the server stopped
/// draining, which is exactly when it is busy indexing.
#[tauri::command]
pub async fn rust_lsp_notify(method: String, params: Value) -> Result<(), String> {
    if !notification_allowed(&method) {
        return Err(format!("{method} is not allowed: this client is read-only"));
    }
    tauri::async_runtime::spawn_blocking(move || notify(&method, params))
        .await
        .map_err(|e| format!("the Rust language server thread died: {e}"))?
}

// ---------------------------------------------------------------- tests

#[cfg(test)]
mod tests {
    use super::*;

    fn drain(d: &mut FrameDecoder) -> Vec<String> {
        let mut out = Vec::new();
        while let Ok(Some(m)) = d.next_message() {
            out.push(m);
        }
        out
    }

    #[test]
    fn decodes_one_whole_message() {
        let mut d = FrameDecoder::new();
        d.push(&encode("{\"a\":1}"));
        assert_eq!(drain(&mut d), vec!["{\"a\":1}".to_string()]);
    }

    #[test]
    fn header_split_across_chunks() {
        let mut d = FrameDecoder::new();
        let wire = encode("{\"ok\":true}");
        // Cut inside the words "Content-Length", which is where a real pipe
        // read loves to cut.
        d.push(&wire[..7]);
        assert_eq!(d.next_message().unwrap(), None);
        d.push(&wire[7..12]);
        assert_eq!(d.next_message().unwrap(), None);
        d.push(&wire[12..]);
        assert_eq!(drain(&mut d), vec!["{\"ok\":true}".to_string()]);
    }

    #[test]
    fn body_split_across_chunks() {
        let mut d = FrameDecoder::new();
        let payload = "{\"long\":\"".to_string() + &"x".repeat(5000) + "\"}";
        let wire = encode(&payload);
        let mut collected = Vec::new();
        for piece in wire.chunks(97) {
            d.push(piece);
            collected.extend(drain(&mut d));
        }
        // Exactly one message, and only after the last chunk: a decoder that
        // emitted early would show up here as a short or duplicated payload.
        assert_eq!(collected, vec![payload]);
    }

    #[test]
    fn body_is_withheld_until_complete() {
        let mut d = FrameDecoder::new();
        let wire = encode("{\"v\":123456}");
        d.push(&wire[..wire.len() - 1]);
        assert_eq!(d.next_message().unwrap(), None, "a truncated body must not be emitted");
        d.push(&wire[wire.len() - 1..]);
        assert_eq!(d.next_message().unwrap(), Some("{\"v\":123456}".to_string()));
    }

    #[test]
    fn two_messages_in_one_chunk() {
        let mut d = FrameDecoder::new();
        let mut wire = encode("{\"n\":1}");
        wire.extend_from_slice(&encode("{\"n\":2}"));
        d.push(&wire);
        assert_eq!(drain(&mut d), vec!["{\"n\":1}".to_string(), "{\"n\":2}".to_string()]);
    }

    #[test]
    fn unknown_headers_are_ignored() {
        let mut d = FrameDecoder::new();
        d.push(b"Content-Type: application/vscode-jsonrpc\r\nContent-Length: 2\r\n\r\n{}");
        assert_eq!(drain(&mut d), vec!["{}".to_string()]);
    }

    #[test]
    fn bad_header_is_fatal() {
        let mut d = FrameDecoder::new();
        d.push(b"Content-Length: banana\r\n\r\n{}");
        let e = d.next_message().unwrap_err();
        assert!(e.contains("bad Content-Length"), "{e}");
    }

    #[test]
    fn header_without_length_is_fatal() {
        let mut d = FrameDecoder::new();
        d.push(b"X-Whatever: 1\r\n\r\n{}");
        assert!(d.next_message().unwrap_err().contains("without Content-Length"));
    }

    #[test]
    fn header_line_without_colon_is_fatal() {
        let mut d = FrameDecoder::new();
        d.push(b"garbage\r\n\r\n{}");
        assert!(d.next_message().unwrap_err().contains("malformed"));
    }

    #[test]
    fn oversized_header_is_fatal_rather_than_unbounded() {
        let mut d = FrameDecoder::new();
        d.push(&vec![b'a'; MAX_HEADER_BYTES + 1]);
        assert!(d.next_message().unwrap_err().contains("no LSP header"));
    }

    #[test]
    fn oversized_body_is_refused_before_allocation() {
        let mut d = FrameDecoder::new();
        d.push(format!("Content-Length: {}\r\n\r\n", MAX_MESSAGE_BYTES + 1).as_bytes());
        assert!(d.next_message().unwrap_err().contains("over the limit"));
    }

    #[test]
    fn encode_counts_bytes_not_characters() {
        // "é" is two bytes and one character: a client that counts characters
        // truncates every message containing one.
        let wire = encode("{\"s\":\"é\"}");
        let text = String::from_utf8(wire).unwrap();
        assert!(text.starts_with("Content-Length: 10\r\n\r\n"), "{text}");
        let mut d = FrameDecoder::new();
        d.push(text.as_bytes());
        assert_eq!(drain(&mut d), vec!["{\"s\":\"é\"}".to_string()]);
    }

    #[test]
    fn uri_escapes_spaces_and_keeps_separators() {
        assert_eq!(
            path_to_uri(Path::new("/Volumes/Noxalis Lab/a+b/main.rs")),
            "file:///Volumes/Noxalis%20Lab/a%2Bb/main.rs"
        );
    }

    #[test]
    fn uri_escapes_non_ascii_as_utf8_bytes() {
        // Percent-encoding is defined on BYTES, not on characters.
        assert_eq!(path_to_uri(Path::new("/tmp/café")), "file:///tmp/caf%C3%A9");
    }

    #[test]
    fn allowlist_refuses_the_command_family() {
        assert!(request_allowed("textDocument/hover"));
        assert!(request_allowed("textDocument/rename"));
        assert!(!request_allowed("workspace/executeCommand"));
        assert!(!request_allowed("rust-analyzer/runFlycheck"));
        assert!(!request_allowed("textDocument/formatting"));
        assert!(notification_allowed("textDocument/didChange"));
        assert!(!notification_allowed("textDocument/didSave"));
        assert!(!notification_allowed("workspace/didChangeConfiguration"));
    }

    #[test]
    fn init_params_disable_everything_that_executes_code() {
        let p = initialize_params(
            Path::new("/w"),
            "file:///w",
            Path::new("/bundle/library"),
            Some(Path::new("/opt/rust")),
        );
        let opts = &p["initializationOptions"];
        assert_eq!(opts["cargo"]["buildScripts"]["enable"], json!(false));
        assert_eq!(opts["procMacro"]["enable"], json!(false));
        assert_eq!(opts["checkOnSave"], json!(false));
        assert_eq!(opts["cargo"]["sysroot"], json!("/opt/rust"));
        assert_eq!(opts["cargo"]["sysrootSrc"], json!("/bundle/library"));
        // Regression guard for the bisected trap: this key silently stops the
        // crate graph from ever loading.
        assert!(opts["cargo"].get("autoreload").is_none());
        assert_eq!(p["capabilities"]["general"]["positionEncodings"], json!(["utf-16"]));
    }

    #[test]
    fn init_params_carry_a_null_sysroot_when_there_is_no_rustc() {
        let p = initialize_params(Path::new("/w"), "file:///w", Path::new("/bundle/library"), None);
        assert_eq!(p["initializationOptions"]["cargo"]["sysroot"], Value::Null);
        // The bundled sources are still declared: std must resolve either way.
        assert_eq!(
            p["initializationOptions"]["cargo"]["sysrootSrc"],
            json!("/bundle/library")
        );
    }

    #[test]
    fn position_encoding_other_than_utf16_is_refused() {
        assert!(check_position_encoding(&json!({"capabilities": {"positionEncoding": "utf-8"}}))
            .is_err());
        assert!(check_position_encoding(&json!({"capabilities": {"positionEncoding": "utf-16"}}))
            .is_ok());
        // Absent is the 3.16 default, which is utf-16.
        assert!(check_position_encoding(&json!({"capabilities": {}})).is_ok());
    }

    #[test]
    fn note_is_silent_when_the_toolchain_is_complete() {
        assert!(note_for(true, true).is_none());
        assert!(note_for(false, true).unwrap().contains("no cargo"));
        assert!(note_for(false, false).unwrap().contains("no Rust toolchain"));
    }

    #[test]
    fn error_responses_keep_the_code() {
        assert_eq!(
            lsp_error_message(&json!({"code": -32601, "message": "unknown"})),
            "unknown (LSP error -32601)"
        );
    }

    #[test]
    fn status_is_empty_when_nothing_runs() {
        // Only true when no other test in this binary left a server behind;
        // start() is exercised in the ignored live test, never here.
        let s = status();
        if !s.running {
            assert!(s.root.is_none() && s.pid.is_none());
        }
    }

    #[test]
    fn starting_on_a_missing_folder_fails_closed() {
        let e = start(Path::new("/nope/definitely/not/here"), Box::new(|_| {})).unwrap_err();
        assert!(e.contains("not a folder"), "{e}");
    }

    /// The real subprocess, end to end. Not part of the default run: it needs
    /// the bundled tooling, it spawns a process and it indexes a crate.
    ///
    ///   cargo test --lib -- --ignored --nocapture lsp::tests::live
    ///
    /// What it proves, in order of what would actually break in production:
    ///   1. the bundled binary starts, initializes and agrees on utf-16;
    ///   2. `std::` RESOLVES. A hover on `Duration` that comes back mentioning
    ///      core::time is the only evidence that the sysroot wiring works, and
    ///      it is the whole reason the bundle carries 70 MB of sources;
    ///   3. the file it just analysed reports NO unresolved-import errors. That
    ///      is the failure this feature exists to avoid: a server with no
    ///      sysroot underlines every use of std and is worse than no server;
    ///   4. stop() actually reaps the process.
    #[test]
    #[ignore = "spawns the bundled rust-analyzer against this crate"]
    fn live_server_resolves_std_and_reports_clean() {
        // GALACTUS_LSP_TEST_ROOT lets the same test drive a checkout other than
        // the crate it was compiled in.
        let root = std::env::var("GALACTUS_LSP_TEST_ROOT")
            .map(PathBuf::from)
            .unwrap_or_else(|_| PathBuf::from(env!("CARGO_MANIFEST_DIR")));
        let events = std::sync::Arc::new(Mutex::new(Vec::<Value>::new()));
        let seen = events.clone();
        let st = start(
            &root,
            Box::new(move |v| seen.lock().unwrap_or_else(|e| e.into_inner()).push(v)),
        )
        .expect("server must start");
        println!("server:     {:?}", st.server);
        println!("sysroot:    {:?}", st.sysroot);
        println!("sysrootSrc: {:?}", st.sysroot_src);
        println!("cargo: {}  note: {:?}", st.cargo, st.note);
        assert!(st.running);
        let pid = st.pid.expect("a running server has a pid");

        // Any file will do for the outline, but resolution only happens for a
        // file that is IN THE MODULE TREE: rust-analyzer refuses to analyse a
        // .rs nobody declared with `mod`, and a test pointed at an orphan file
        // reports a broken sysroot when the sysroot is fine.
        let file = root.join(
            std::env::var("GALACTUS_LSP_TEST_FILE").unwrap_or_else(|_| "src/pylang.rs".into()),
        );
        let text = std::fs::read_to_string(&file).unwrap();
        let uri = path_to_uri(&file);
        notify(
            "textDocument/didOpen",
            json!({"textDocument": {"uri": uri, "languageId": "rust", "version": 1, "text": text}}),
        )
        .unwrap();

        // The outline is answered from the syntax tree alone, so it comes back
        // before indexing and proves nothing about resolution. Asserted anyway
        // because it is the cheapest signal that the pipe works at all.
        let symbols = request(
            "textDocument/documentSymbol",
            json!({"textDocument": {"uri": uri}}),
            DEFAULT_REQUEST_DEADLINE,
        )
        .expect("documentSymbol must answer");
        let outline = symbols.as_array().map(|a| a.len()).unwrap_or(0);
        println!("documentSymbol: {outline} top level symbols");
        assert!(outline > 0);

        // Line of `use std::time::{Duration, Instant};`, hovering the D.
        let (line, character) = locate(&text, "use std::time::{Duration").expect("import line");
        let character = character + "use std::time::{".chars().count() as u64;

        // Generous: a cold run reads cargo metadata and scans a few hundred
        // dependency roots before anything resolves. Warm, this takes seconds.
        let started = Instant::now();
        let deadline = started + Duration::from_secs(900);
        let mut hover_text = String::new();
        while Instant::now() < deadline {
            let hover = request(
                "textDocument/hover",
                json!({"textDocument": {"uri": uri}, "position": {"line": line, "character": character}}),
                DEFAULT_REQUEST_DEADLINE,
            )
            .unwrap_or(Value::Null);
            hover_text = hover["contents"]["value"].as_str().unwrap_or("").to_string();
            if hover_text.contains("Duration") {
                break;
            }
            std::thread::sleep(Duration::from_millis(500));
        }
        println!("hover resolved after {:?}", started.elapsed());
        println!("hover on Duration:\n{}", hover_text.trim());
        for v in events.lock().unwrap_or_else(|e| e.into_inner()).iter() {
            if v["kind"] == json!("log") {
                println!("server log: {}", v["params"]["message"].as_str().unwrap_or(""));
            }
        }
        assert!(
            hover_text.contains("Duration"),
            "std did not resolve: the sysroot wiring is broken"
        );

        // Wait for a diagnostics publication about this exact file.
        let mut errors: Vec<String> = Vec::new();
        let mut published = 0usize;
        let deadline = Instant::now() + Duration::from_secs(300);
        while Instant::now() < deadline {
            {
                let log = events.lock().unwrap_or_else(|e| e.into_inner());
                let mine: Vec<&Value> = log
                    .iter()
                    .filter(|v| v["kind"] == json!("diagnostics") && v["params"]["uri"] == json!(uri))
                    .collect();
                published = mine.len();
                if let Some(last) = mine.last() {
                    errors = last["params"]["diagnostics"]
                        .as_array()
                        .map(|a| {
                            a.iter()
                                .filter(|d| d["severity"] == json!(1))
                                .map(|d| d["message"].as_str().unwrap_or("").to_string())
                                .collect()
                        })
                        .unwrap_or_default();
                    break;
                }
            }
            std::thread::sleep(Duration::from_millis(500));
        }
        println!("publishDiagnostics for this file: {published}, errors: {}", errors.len());
        for e in errors.iter().take(5) {
            println!("  error: {e}");
        }
        assert!(published > 0, "the server never published diagnostics for the open file");
        assert!(errors.is_empty(), "the server reported errors on a file that compiles");

        stop();
        assert!(!status().running);
        // The child must be gone, not merely forgotten.
        let alive = Command::new("kill")
            .args(["-0", &pid.to_string()])
            .output()
            .map(|o| o.status.success())
            .unwrap_or(false);
        println!("pid {pid} still alive after stop: {alive}");
        assert!(!alive, "stop() left rust-analyzer running");
    }

    /// Zero-based line and character of the first occurrence of `needle`.
    /// Characters are counted in utf-16 units, like the protocol.
    fn locate(text: &str, needle: &str) -> Option<(u64, u64)> {
        for (n, line) in text.lines().enumerate() {
            if let Some(byte) = line.find(needle) {
                let character = line[..byte].encode_utf16().count() as u64;
                return Some((n as u64, character));
            }
        }
        None
    }
}
